### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by rodrigograca31** [illvart/gatsby-plugin-minify-html#4]
Please use `html-minifier-terser` instead of `html-minifier` the last one is outdated and doesn't support ES6.

https://github.com/terser/html-minifier-terser

More info here: https://github.com/kangax/html-minifier/issues/1040

**Comment by rodrigograca31** [comment]
@illvart should I make a PR so that its easy to accept and merge?

**Comment by illvart** [comment]
> @illvart should I make a PR so that its easy to accept and merge?

Yes, you can change our code, test locally and make a PR by following [CONTRIBUTING](https://github.com/illvart/gatsby-plugin-minify-html/blob/master/docs/CONTRIBUTING.md).
